%YAML:1.0
# config for sportsfield

imu_topic: "/imu0"
feature_topic: "/stereo_tracker/stereo_feature"

cam_nums: 2
cam_left_file_path: "/home/lcw/VIO/ws_ingvio/src/config/sportsfield/stereo_left_config.yaml"
cam_right_file_path: "/home/lcw/VIO/ws_ingvio/src/config/sportsfield/stereo_right_config.yaml"

max_sliding_window_poses: 20
max_landmark_features: 25

enable_gnss: 1

noise_gyro: 0.005
noise_accel: 0.05
noise_bias_gyro: 0.001
noise_bias_accel: 0.01
noise_rcv_clockbias: 2.0
noise_rcv_clockbias_randomwalk: 0.2

init_cov_rot: 0.05
init_cov_pos: 0.1
init_cov_vel: 0.5
init_cov_bg: 0.01
init_cov_ba: 0.08
init_cov_ext_rot: 8e-03
init_cov_ext_pos: 5e-04
init_cov_rcv_clockbias: 3.0
init_cov_rcv_clockbias_randomwalk: 1.0
init_cov_yof: 0.03

gravity_norm: 9.8
max_imu_buffer_size: 1000
init_imu_buffer_sp: 100
