%YAML:1.0
# config for sportsfield

imu_topic: "/imu0"
feature_topic: "/stereo_tracker/stereo_feature"

cam_nums: 2
cam_left_file_path: "/home/lcw/VIO/ws_ingvio/src/config/sportsfield/stereo_left_config.yaml"
cam_right_file_path: "/home/lcw/VIO/ws_ingvio/src/config/sportsfield/stereo_right_config.yaml"

max_sliding_window_poses: 27
is_key_frame: 1
max_landmark_features: 0

enable_gnss: 0

noise_gyro: 0.004
noise_accel: 0.08
noise_bias_gyro: 0.0002
noise_bias_accel: 0.008
noise_rcv_clockbias: 2.0
noise_rcv_clockbias_randomwalk: 0.2

init_cov_rot: 0.0
init_cov_pos: 0.0
init_cov_vel: 0.25
init_cov_bg: 0.01
init_cov_ba: 0.01
init_cov_ext_rot: 1.8e-02
init_cov_ext_pos: 2e-03
init_cov_rcv_clockbias: 2.0
init_cov_rcv_clockbias_randomwalk: 1.0
init_cov_yof: 0.015

gravity_norm: 9.8
max_imu_buffer_size: 1000
init_imu_buffer_sp: 300

trans_thres: 0.25
huber_epsilon: 0.01
conv_precision: 5e-07
init_damping: 1e-03
outer_loop_max_iter: 10
inner_loop_max_iter: 10
max_depth: 40.0
min_depth: 0.2
max_baseline_ratio: 80.0

chi2_max_dof: 150
chi2_thres: 0.95
visual_noise: 0.035
frame_select_interval: 18

gnss_ephem_topic: "/ublox_driver/ephem"
gnss_glo_ephem_topic: "/ublox_driver/glo_ephem"
gnss_meas_topic: "/ublox_driver/range_meas"
gnss_iono_params_topic: "/ublox_driver/iono_params"
rtk_gt_topic: "/ublox_driver/receiver_lla"

gnss_elevation_thres: 20.0
gnss_psr_std_thres: 8.0
gnss_dopp_std_thres: 8.0
gnss_track_num_thres: 20

use_fix_time_offset: 0
gnss_local_offset: -18.0

gv_align_batch_size: 45
gv_align_max_iter: 10
gv_align_conv_epsilon: 1e-05       
gv_align_vel_thres: 0.4
